### ISSUE TITLE
Проблема с вставкой инлайновых скриптов

### ISSUE THREAD

**Issue by adm1t** [nicothin/NTH-start-project#102]
Есть необходимость заинлайнить скрипт после подключения js-бандла. 

```
block page-bottom
  script(src='js/bundle.js')
  script
    include ../js/some-script.js
```

При такой записи содержимое второго тега script при сборке остаётся пустым (путь к файлу корректен; если убрать подключение бандла, то скрипт инлайнится как и должен). Это какие-то ограничения для разметки в pug или все же баг в сборке?

**Comment by npofopr** [comment]
Там бывало, что доктайп в конфиге к пагу надо указывать было

```
let pugOption = {
  data: { repoUrl: 'https://bitbucket.org/npofopr/datakit-food' },
  filters: { 'show-code': filterShowCode },
  doctype: 'html'
```

**Comment by nicothin** [comment]
Баг сымитировал.
Это связано с компиляцией pug, видимо (сборка на это не влияет).
Попробую поискать причину и устранить ее.

**Comment by nicothin** [comment]
Нет, таки виновата была сборка ))

https://github.com/nicothin/NTH-start-project/commit/2e78fed3ee6762a4fcbe5f52d5ca713e1635f2b0 — вот фикс.
