### ISSUE TITLE
Возможно ли отключить минификацию js?

### ISSUE THREAD

**Issue by webdtim** [nicothin/NTH-start-project#103]
Если возможно, то пожалуйста подскажите как это сделать.
Буду очень признателен.

**Comment by nicothin** [comment]
`npm start`
в `build/js/bundle.js` неминифицированный файл

в чем вопрос?

**Comment by webdtim** [comment]
Нужно отключить переименовывание функций.
Можно не использовать транспиляцию, если необходимо.

**Comment by nicothin** [comment]
> Нужно отключить переименовывание функций.
> Можно не использовать транспиляцию, если необходимо.

В целом, изменения, вносимые в JS делаются вебпаком в ходе выполнения задачи обработки JS.
Видимо, нужно выпиливать сборку JS вебпаком и самостоятельно собирать JS простой конкатенацией файлов (то есть, заметно сменить способ обработки с потерей функциональности менеджера зависимостей). 

Cмотрите `gulpfile.js`: список конкатенируемых js-файлов формируется там (и потом список пишется в `src/js/entry.js`), вы можете перепилить это, к примеру, так: 

1. в самом галпфайле формируем массив js-файлов, которые хотим в сборку
2. устанавливаем что-то типа https://www.npmjs.com/package/gulp-concat
3. переписываем задачу сборки JS с использованием пакета для конкатенации (см. доку `gulp-concat`)
