### ISSUE TITLE
Отсутствие grid-mixins.scss ломает сборку

### ISSUE THREAD

**Issue by erkinaltai** [nicothin/NTH-start-project#104]
Здраствуйте. Вы удалили в этом коммите
github.com/nicothin/NTH-start-project/commit/81a13b261816cc0f7e1051cb19fd9bea15b38cf7
файл grid-mixins.scss
Это ломает весь проект.

**Comment by npofopr** [comment]
добавьте обратно)

**Comment by nicothin** [comment]
> Здраствуйте. Вы удалили в этом коммите
> github.com/nicothin/NTH-start-project/commit/81a13b261816cc0f7e1051cb19fd9bea15b38cf7
> файл grid-mixins.scss
> Это ломает весь проект.

Приветствую. При установке «с нуля» ничего не ломается.

Я решил отказаться от этого (довольно старого) файла с миксинами, т.к. для формирования сеток можно и нужно использовать css grid, а не этот костылик ;)

Если это ломает сборку вашего проекта, проще всего вернуть файл, взяв, к примеру, отсюда: https://raw.githubusercontent.com/nicothin/NTH-start-project/529ee558e440d710999c26480eccf788b290c360/src/scss/mixins/grid-mixins.scss
