### ISSUE TITLE
Как правильно организовать сборку целой страницы?

### ISSUE THREAD

**Issue by artemdrei** [nicothin/NTH-start-project#12]
Добрый день, Николай.
Недавно начал использовать Вашу прекрасную работу -  NTH-start-project. В процессе работы возникли несколько вопросов по правильной организации кода, не могли бы Вы прояснить некоторые моменты?

Как организованы блоки с компонентами вопросов не вызывает. Но как дела обстоят с цельной страницей пока не понятно. 

К примеру создан в корне src файл landing.html. Заинклудил хедер, футер, нужные компоненты. А вот что делать  с секциями не понятно (к примеру about-us, tema и тд):
-  просто писать в landing.html разметку, вставляя где нужно инклудами компоненты можно. Тогда не ясно, где писать стили к этим секциями и добавлять графику + js.
- либо делать под каждую секцию в blocks/about-us и там писать стили + img + js, но тогда blocks превратится в полную кашу. 
- либо в blocks создать папку landing и в нем уже делать разбиение на отдельные html составляющие + img + css + js. Но последующие страницы хоть и будут одной папке (blocks) но будут отсортированы по алфавиту, что тоже не предает структуры, плюс внутри landing будет очень много файлов, что тоже не круто.

Не могли бы прояснить данный  момент, потому что портить красивый стартовый проект уродливыми решениями не хочется.

**Comment by nicothin** [comment]
Любая страница состоит из Блоков.
Стили Блока и его JS должны быть в папке блока (там же могут, по желанию, лежать его картинки, доп. картинки (инлайнящиеся в стилях, к примеру), пример разметки или разметка с микрошаблонизацией и вообще любые другие файлы, относящиеся к этому Блоку).
Инклудить «шапку» и «подвал» страницы стоит из соотв. папок Блоков.

Сам я, зачастую, храню в папке Блока только стили и JS, а разметку пишу прямо в страницах (за исключением повторяющихся идентичных).
