### ISSUE TITLE
Компиляция css в произвольном порядке.

### ISSUE THREAD

**Issue by dimavel** [nicothin/NTH-start-project#17]
Добрый день. Есть проблема, что файл стилей компилирует медиа запросы в разном порядке. Запрос на 768px может находится ниже чем запрос на 480px, приходится перебивать стили каскадом. Не подскажете как решить данную проблему.

![01](https://user-images.githubusercontent.com/18086302/27091639-67e73fce-5069-11e7-9af6-f87ad2e04b8d.png)
![02](https://user-images.githubusercontent.com/18086302/27091638-67e644ca-5069-11e7-840c-b1fd6027e4cc.png)
![03](https://user-images.githubusercontent.com/18086302/27091637-67e49666-5069-11e7-8149-445d28ff30c9.png)

**Comment by nicothin** [comment]
https://github.com/nicothin/NTH-start-project/blob/master/gulpfile.js#L47 — включена сортировка медиаправил.
я всегда иду по пути mobile first, для меня нужно, чтобы сначала шли медиаусловия малых значений, потом больших.
