### ISSUE TITLE
Как добавлять плагины jQuery

### ISSUE THREAD

**Issue by BroFox86** [nicothin/NTH-start-project#22]
Здравствуйте! 

Во-первых, спасибо за этот репозиторий, я многое из него для себя почерпнул. Но у меня остался нерешенным вопрос: каким образом добавляются плагины JQuery в ваш проект?

Допустим нужно внедрить lightbox-плагин для картинок. В роли js-хука используется элемент “section__image-link”. У плагина помимо js-файла есть свои стили и иконки. Первое что приходит в голову при использовании файловой структуры БЭМ (насколько я ее пока понимаю) —  сделать все ресурсы плагина частью блока и разместить их в его папке, при этом «грязно» смешав стили блока со стилями плагина. 

Так делать можно или у Вас какой-то более удобный вариант? Читал по этой теме много материала, но не нашел хороших примеров...

**Comment by nicothin** [comment]
Проще всего:

1. завести блок для плагина (папку в `src/blocks/my-new-block`)
2. разместить в этой папке всё, что нужно плагину: стилевой файл (возможно, лучше переименовать его во что-то вроде `my-new-block.scss`, чтобы иметь возможность использовать там препроцессинг стилей, переменные проекта и т.п.), js-файл (тоже переименовать — имя как у блока-папки), картинки (в `src/blocks/my-new-block/img`, если хотите, чтобы они копировались в папку сборки).
3. поправить в стилевом файле плагина пути к картинкам
4. взять блок в сборку, вписав его имя в [секцию blocks](https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L2)
5. в разметке миксовать блок к тем БЭМ-сущностям, где нужен плагин.
6. инициализировать плагин в js-файлах нужных блоков или в глобальном js-файле.

**Другой вариант, более продвинутый (и рекомендуемый, пожалуй)**:

1. ставить нужный плагин как npm-зависимость с записью его в [соотв. секцию package.json](https://github.com/nicothin/NTH-start-project/blob/master/package.json#L64)
2. брать в сборку его стилевой файл (см. [как сделано сейчас для owl.carousel](https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L64))
3. брать в сборку js-файл плагина (см. [как сделано сейчас для owl.carousel](https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L78))
4. брать в сборку картинки плагина, вписав папку с этими картинками как дополнительный элемент массива [в соотв. секции конфига сборки](https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L86)
5. добавлять классы этого плагина куда нужно (если классы вообще нужно добавлять, собственно)
6. инициализировать плагин в js-файлах блоков, где он нужен или в глобальном js-файле.

**Comment by BroFox86** [comment]
Большое спасибо за ответ! Очень интересно и исчерпывающе, так что вопросов по этому поводу больше нет. Оба способа хороши, но мне больше понравился второй. Буду делать. :)
