### ISSUE TITLE
Gulp version

### ISSUE THREAD

**Issue by ricomen** [nicothin/NTH-start-project#23]
Приветствую Николай.

Если мне память не изменяет, Ваш шаблон "вертелся" на 4 Gulp, из каких соображение откатились на 3.9.1

**Comment by nicothin** [comment]
Приветствую. 
Из-за тормозов при длительной работе вотчеров галпа: на проектах более-менее крупных размеров (точно влияло кол-во CSS-а) спустя 10-15 минут время компиляции начинало прогрессивно увеличиваться на 0.2 - 1 секунд на одну компиляцию, что быстро приводило к невменяемой длительности сборки стилей.
