### ISSUE TITLE
Обработка изображений

### ISSUE THREAD

**Issue by AcidHardcore** [nicothin/NTH-start-project#24]
При попытке обработки изображений выдает ошибку:
 folder=/src/blocks/logo/img npm start img:opt
"folder" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Операционная система - Windows 10
Запускаю из корня проекта.
Что нужно покрутить?

**Comment by nicothin** [comment]
Скрин давайте, ибо неясно в какой среде выполняете команду (попробуйте в gitbash).

**Comment by AcidHardcore** [comment]
gitbash помог, спасибо.  Выполнял в Cmder.exe

**Comment by nicothin** [comment]
Так cmder — обертка для терминалов, внутри можно и повершелл, и cmd.exe, и gitbash запускать )

**Comment by AcidHardcore** [comment]
Ага, я пошел дальше и запустил cmder в середине PHPStorm. Теперь запустил git-bash.

**Comment by nicothin** [comment]
Прям в середине? Да вы МОНСТР! ))

**Comment by AcidHardcore** [comment]
Рад что поднял Вам настроение))
