### ISSUE TITLE
Как можно скомпилировать для работы отдельно блоки ?

### ISSUE THREAD

**Issue by Starushchenko** [nicothin/NTH-start-project#30]
Николай, спасибо за отличный темплейт, всё доступно описано и удобно в использовании. Подскажите пожалуйста технически, как можно дополнительно организовать команду для сборки не привычным способом (img, js, css, страницы), а, скажем, чтобы скомпилировать перечень блоков в какую-нибудь отдельную папку buildBlocks (компонентно для программиста). Чтобы переносились блоки со всем содержимым, скомпилированным css и, возможно, подключенным js ? Наверное, всё можно сделать обычным способом, но может вы что-то подскажете

**Comment by nicothin** [comment]
Не удавливаю.
Задача — скомпилировать стили только конкретного одного блока и на выходе получить что-то вроде `dist/blocks/text-field/` со стилями, картинками и JS?
Если да, то стилевые переменные брать общие, или достаточно дефолтных, указанных в каждом стилевом файле?
(разруливать JS-зависимости придется руками. хотя их у меня тут кот наплакал)

**Comment by Starushchenko** [comment]
Да, задача - получить блок со скомпилированными стилями. Стилевые переменные, думаю, заменять на общие значения, как если бы это было в общем файле style.css. По сути, тут переменные - главная соль (иначе, если нужно отдать блок программисту, можно в принципе отдавать папку в текущем виде). Необходимые для блока js-библиотеки - это второстепенная вещь (зависимости блока можно описать хотя бы в readme), и грубо говоря, библиотеки обычно подключаются в отдельном от блока месте. Я имею в виду практический случай, когда готова верстка блока со всей его модульностью и этот блок в виде модуля нужно отдать программисту в скомпилированном виде. Иначе, если шаблонизатор на сайте позволяет хранить стилевые файлы для блоков (модулей) отдельно (с последующим объединением в процессе загрузки страницы, у меня такой случай), то немного бессмысленно искать и выделять стили, относящиеся к блоку из скомпилированного style.min.css 🙂 Так или иначе команда сборки блоков отдельно никак не помешает вашей наработке 🙂

**Comment by nicothin** [comment]
Реализация же не выглядит сложной: 
- обходим циклом [объект с нужными в проекте блоками](https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L3-L58), для каждого имеем название (совпадает с именем папки/компилируемого файла)
  - создаем контент компилирующегося файла (импорт файла с переменными, импорт примеси и импорт стилевого файла обрабатываемого блока)
  - компилируем получившийся файл в `dist/ИМЯБЛОКА/ИМЯБЛОКА.scss`
  - копируем туда же картинки блока и скрипты

Я бы писал это все в галпфайле. Там сейчас похожим образом создается `style.scss`
