### ISSUE TITLE
Как подключить css-фреймворк (Bootstrap/Foundation)

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#34]
А можно ли добавить целый фреймворк?)
Например, foundation, bootstrap тот же.

Интересно именно добавление scss. 
Пробовал добавить 
`"../../node_modules/foundation-sites/scss/foundation.scss"`
но безрезультатно, но и другие вариации пробовал. 

Или не всё так просто?) 

Т.е. чтобы именно все veriables (настройки) были от foundation.

**Comment by nicothin** [comment]
попробуйте поставить фреймворк как зависимость, потом подключить его файлы в https://github.com/nicothin/NTH-start-project/blob/master/projectConfig.json#L62 
соответственно, свои переменные/примеси и прочее оттуда можно/нужно убрать.

пару месяцев назад пробовал подключить и скомпилировать Бытстрап, проблем не заметил.

п.с.: «безрезультатно» — крайне плохое описание возникшей проблемы ;)

**Comment by npofopr** [comment]
Через зависимости и пробую.
С бутстрапом действительно проблем нет. Подключил из node_modules `bootstrap.scss` и всё заработало.

А вот с foundation, дальше его комментария
```
/**
 * Foundation for Sites by ZURB
 * Version 6.4.4-rc1
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */
```
ничего нет. 
Т.е. файл схватывается, но внутренности не тянутся.

Попробовал из  foundation.scss убрать подключаемые Dependencies, но то же самое.

Ставил это `npm install foundation-sites`.

**Comment by nicothin** [comment]
Установил, запустил сборку стилей, тоже вижу лишь коммент.
Прошелся по коду компилируемых файлов, выяснил, что foundation-sites — набор примесей. Если их не вызывать, то и не будет никаких стилей ))

**Comment by npofopr** [comment]
Вроде у них у всех так) 
foundation.scss основной с инклудами на всё остальное. 

Не подскажите тогда, как их вызвать все?)

**Comment by nicothin** [comment]
Без понятия. Курить документацию, видимо.
