### ISSUE TITLE
Еще более мощный Pug за счет bemto

### ISSUE THREAD

**Issue by v1z** [nicothin/NTH-start-project#38]
Николай, так как Вы перешли на Pug, возможно имеет смысл посмотреть в сторону bemto (https://github.com/kizu/bemto). Код станет в разы приятнее читать, также избавит от излишнего нейминга (кейсы с 2-3 модификаторами)

**Comment by nicothin** [comment]
Да, присматривался к bemto, даже упоминал его на занятиях.
Однако, пока несколько неочевидны преимущества. Попробую один проект сделать просто на pug и один с bemto, посмотрю стоит ли обратиться к нему.
