### ISSUE TITLE
Попробовать разнести gulp-задачи по разным файлам, сравнить производительность

### ISSUE THREAD

**Issue by nicothin** [nicothin/NTH-start-project#41]
Освежить знания по теме с пом-ю скринкаста Ильи Кантора про gulp :)

**Comment by ranwise** [comment]
так скринкаст скорее всего устарел уже

**Comment by nicothin** [comment]
с чего бы ему устареть?
он про 4ю версию записан. она еще в релиз не вышла.

**Comment by nicothin** [comment]
Отказался, т.к. навскидку реального профита не выходит: подавляющая часть задач запускается при старте сервера, ожидаемая экономия времени — 5-10% — не стоит трудозатрат.
