### ISSUE TITLE
Тестировать с gulp 4-й версии

### ISSUE THREAD

**Issue by nicothin** [nicothin/NTH-start-project#47]
Ранее был странный глюк на винде: по ходу работы прогрессивно увеличивалось время, затрачиваемое на компиляцию стилей. Если при старте была пара секунд, то минут через 10 работы становилось уже в районе 6 и далее время увеличивалось при несущественном усложнении кодовой базы.

**Comment by ranwise** [comment]
решил такую проблему у себя заменой в путях к scss с `'**/*.scss'` на `'*.scss'` и время перестало расти

**Comment by nicothin** [comment]
@ranwise буду знать, спасибо!

**Comment by ranwise** [comment]
[тут](https://toster.ru/q/380260) нашел решение

**Comment by nicothin** [comment]
Тестировал, описанная проблема сохраняется. Нужно попробовать отказаться от сегмента `**/` в путях вотчера.

**Comment by nicothin** [comment]
Перетащил автоматику на gulp 4. 
Удалось обойтись без `**/` для вотчеров.
