### ISSUE TITLE
Должен быть вотч на изменение любых scss файлов, должен происходить ребилд.

### ISSUE THREAD

**Issue by maliyshock** [nicothin/NTH-start-project#49]
Сейчас, когда я меняю что-то в миксинах, ребилда не происходит. https://cl.ly/0y440R231Z0E
Возвращаюсь к scss, что в блоке https://cl.ly/2E3R2C1t1N3M

**Comment by nicothin** [comment]
https://github.com/nicothin/NTH-start-project/commit/c32de350615c917f2e2e9cc8e9398473e8062cfe
