### ISSUE TITLE
Динамический alert

### ISSUE THREAD

**Issue by vostok1961** [nicothin/NTH-start-project#5]
Добрый день.
Как сделать, чтобы работала кнопка закрытия в alert, который формируется таким способом: 
```$("#msg").html('<div class="alert alert--danger"><button class="alert__close" aria-label="Close">×</button><p>сообщение</p></div>');``` ?

**Comment by nicothin** [comment]
Использовать делегированный вызов для отслеживания нажатия кнопки закрытия.
