### ISSUE TITLE
 -webkit-font-smoothing: antialiased;

### ISSUE THREAD

**Issue by maliyshock** [nicothin/NTH-start-project#50]
Эту штуку можно добавить в типографику, она здорово улучшает шрифты на маках.

**Comment by nicothin** [comment]
http://take.ms/MqmS4 —  OSX
подскажите, в чем здоровье улучшения шрифта?

**Comment by maliyshock** [comment]
Хм... буквально только что, без этого свойства, шрифт выглядел жирнее. И это не единичный случай когда антиалиасинг здорово исправлял ситуацию.
Однако, сейчас я тоже не вижу разницы.
Либо у меня припадок и я глючу, либо что-то здесь не так.)

**Comment by nicothin** [comment]
В Сафари происходит некоторое изменение визуальной плотности, однако чтобы его заметить, нужно серьезно приглядываться ))
