### ISSUE TITLE
Время сборки стилей

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#53]
Windows 10 64x.
node 9.5.0
npm 5.6.0

Сборка стилей идёт ~15-30с.
Если добавить ещё с десяток блоков = стилей, может затянуться на пару минут.

Это в чистом виде, т.е. скачиваю проект, делаю `npm i` и пробую.
После обновления `packages` тоже самое.

Пробовал ещё в Виндовом bash, тоже самое.
sdd\ hdd тоже ситуации не меняло.

Вопрос скорее к тем кто пользуется/ сталкивался) 
Виндовая проблема или может дело в чём-то другом?

**Comment by nicothin** [comment]
Холодная сборка проекта на винде реально долгая. Такова архитектура ОС...
И да, (после недавнего обновления винды, других вариантов не вижу) скорость сборки эпически просела. Сейчас при запущеном автомате, 17 секунд на сборку стилей :(
Если запустить `npm start style` - это 23 сек. у меня.

**Comment by nicothin** [comment]
Время в секундах.

Замеры на данный момент, без изменений:

`time npm start style`: 24.6,  25.4, 25.4
`time npm start pug`: 8.1, 7.8, 7.9
`time npm start js`: 6.1, 6.2, 6.2
`time npm start sprite:svg`: 9.3, 6.5, 6.2
`time npm start sprite:png`: 17.0, 6.9, 6.8
`time npm start clean`: 5.8, 5.8, 6.1
`time npm run build`: 52.8, 50.0, 48.3

Компиляция стилей при запущенном сервере по изменению произвольного scss-файла: 18, 17, 18

**Comment by erkinaltai** [comment]
Сборку файла стилей тормозит postCSS плагин - imageInliner.

**Comment by nicothin** [comment]
Точно
Без него: 
`time npm start style`: 6.6
`time npm run build`: 31.7
