### ISSUE TITLE
Did you forget to signal async completion?

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#54]
```
[15:49:33] Размер style.min.css 395 kB
[15:49:33] Finished 'style' after 7.02 s
[15:49:33] The following tasks did not complete: build, <parallel>, style:single
[15:49:33] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
```
Windows 10.
Gulp 4.0,
node 9.5.0

Бывала ли такая ошибка? 
Обрывается после сборки стилей я так понимаю.

Кеш npm чистил, сам gulp удалял/ устанавливал.

**Comment by npofopr** [comment]
Путём исключения `build` тасков, выяснилось, что падает на `'style:single'`

Собственно, если 
```
"singleCompiled": [
		"./src/scss/blocks-library.scss"
	],
```
не пустой, то всё работает. 
Если сборку `blocks-library.scss` убирать, то ошибка.

**Comment by npofopr** [comment]
Не знаю, верно не верно, добавил `callback`, как в `copiedCss`, всё заработало)
Всем спасибо :-)

**Comment by nicothin** [comment]
https://github.com/nicothin/NTH-start-project/commit/0b88a027bd534f164240879d3b9c162bc479a250
спасибо за наводку на вариант исправления.
