### ISSUE TITLE
ES6 и ошибка сборки/ минификации JS

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#55]
Может быть добавить что-то вроде:

```
.pipe(gulpIf(!isDev, uglify().on('error', function(e){console.log(e);})))
```

В сборку попал JS файл с ES6, и не понятно было поначалу из-за чего рушится сборка и минификация JS.

**Comment by nicothin** [comment]
ok https://github.com/nicothin/NTH-start-project/commit/1ad8339bd35f78296f92373301138e988cb8edbc
