### ISSUE TITLE
Блок модального окна: Сокрытие контента при переполнении

### ISSUE THREAD

**Issue by Odisseya** [nicothin/NTH-start-project#60]
При переполнении мод.окна контентом скрывается _верхняя_ часть контента, проскроллить контент до начала становится невозможно. Происходит из-за вертикальной флекс-центровки.  
Скрин: https://prnt.sc/j5476k

**Comment by nicothin** [comment]
Спасибо, решу.

**Comment by Odisseya** [comment]
Николай, и вам огромное спасибо за то, что делитесь опытом, наработками и за отзывчивость.

**Comment by nicothin** [comment]
Поправил
