### ISSUE TITLE
Вынести ВСЕ блоки в отдельную библиотеку, по умолчанию в сборку не брать

### ISSUE THREAD

**Issue by nicothin** [nicothin/NTH-start-project#66]
Но хочется иметь возможность быстро взять в сборку блок из библиотеки (скажем, консольной командой добавлять в сборку 1 или много блоков).

**Comment by nicothin** [comment]
- отдельно собирать библиотеку, отдельно — проектные страницы
- консольной командой создавать 1 или несколько блоков
- консольной командой добавлять 1 или несколько блоков в проект
- консольной командой убирать 1 или несколько блоков из проекта

**Comment by npofopr** [comment]
> Сейчас осваиваю webpack и планирую всё перетащить на реакт или вью

Может видели, недавно наткнулся на такую статью https://nystudio107.com/blog/an-annotated-webpack-4-config-for-frontend-web-development 
Вдруг чем-то полезно будет. 

На винде у меня правда не собрался проект))
