### ISSUE TITLE
Вопрос: Как блоки берутся в сборку?

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#72]
> Импорты файлов БЭМ-блоков, упомянутых в секции alwaysAddBlocks файла config.js. Таким образом, можно взять в сборку любой блок, даже если его css-класс не упоминается в разметке страниц.

Правильно понимаю, 
1. что если у меня создан Блок `test` и он подключен в секции `alwaysAddBlocks`, 
2. в стилях этого блока указан `.test2 {...}` т.е. класс отличается от названия блока
3. то стили из этого блока должны подключаться на любой странице? 

т.е. в конфиге подключен блок `test`, а на странице есть блок с классом `.test2` 
В теории, стили должны подключиться?)

**Comment by nicothin** [comment]
В стилях блока `test` не может быть класса `.test2`. Это не БЭМ.
Какие селекторы взяты в сборку можно смотреть в build/css/ в стилевом файле.

Если хоть на одной странице есть селектор `.test2`, при сборке стилей будет искаться `src/blocks/test2/test2.scss` и, если существует, будет взят в сборку.
Если в конфиге указано брать блок `test`, при сборку стилей будет искаться `src/blocks/test/test.scss` и, если существует, будет взят в сборку.

**Comment by npofopr** [comment]
Ну вот собственно не попадает. 
Просто создаю блок `test` , содержимое:

```
.test {
  $block-name: &; // #{$block-name}__element
}
.test2 {
  color: pink;
}
```

в index.pug добавляю:

```
div.test2
    p test test style
```

Ну и собственно в конфиге добавлено:

```
"alwaysAddBlocks": [
    "test",
  ],
```

**Comment by nicothin** [comment]
Должно работать. Ссылку на репозиторий с этим кодом дайте.

**Comment by npofopr** [comment]
[Ссылка](https://github.com/npofopr/NTH-start-project-test/commit/1bf9418fa2c6a360f215f7ddc2045cd996a8497e)

**Comment by nicothin** [comment]
Баг, однако ))
Исправлю.
