### ISSUE TITLE
Зачем нужны относительные пути к gulp в package.json?

### ISSUE THREAD

**Issue by Rigwarl** [nicothin/NTH-start-project#8]
ведь вместо `"start": "./node_modules/.bin/gulp"`
можно написать `"start": "gulp"`

**Comment by nicothin** [comment]
Не помню. Что-то тестил, что-то не работало. Надо бы убрать, да.

**Comment by nicothin** [comment]
Кажется, `cross-env` не работал без них.
Для стартовой команды убрал.
