### ISSUE TITLE
Ошибка после изменения layout.pug и index.pug

### ISSUE THREAD

**Issue by Webrote** [nicothin/NTH-start-project#80]
Николай. приветствую.
Помоги, пожалуйста, разобраться с проблемой. Клонирую твой проект. Меняю только два файла:
layout.pug и index.pug. Появляется сообщение об ошибке. Не могу понять в чем дело. Причем эта ошибка не возникает при запущенном сервере. Только когда останавливаешь и запускаешь заново.

![](https://user-images.githubusercontent.com/18188728/51840954-85113800-231e-11e9-8d81-13bc9cd6b667.JPG)

**Comment by nicothin** [comment]
Без описания окружения повторить не смогу точно. Ранее такого не видел.
Судя по выводу, терминал — не bash, окружение — винда, проблема с кипированием файлов (пути для пакета `cpy`).
Использование bash-терминала, к примеру, gitbash, приходящий вместе с git, может помочь.

**Comment by nicothin** [comment]
Фикс: https://github.com/nicothin/NTH-start-project/commit/f94af4d35814d3b80795057a8a5c88815a9f182c

**Comment by Webrote** [comment]
Благодарю!
