### ISSUE TITLE
Owl.carousel

### ISSUE THREAD

**Issue by Webrote** [nicothin/NTH-start-project#85]
Николай, подскажи пожалуйста, пытаюсь подключить owl.carousel
(кстати, почему ты его убрал из сборки? вроде лицензия не менялась)
Так вот, не получается подключить.
Как это по правильному сделать?

Делаю, что то примерно такое:

const ready = require('../../js/utils/documentReady.js');
const $ = require('jquery');
const owlCarousel = require('owl.carousel');

ready(function () {
	var promoSlider = $("#promo");
	promoSlider.owlCarousel({
		items: 1,
		nav: false,
		dots: true,
		dotsContainer: '#main-slider-control .slider-control__dots',
	});
});

Браузер ругается:
bundle.js:71 Uncaught TypeError: Cannot read property 'fn' of undefined

**Comment by nicothin** [comment]
Привет
Убрал, чтобы не грузить стартовую библиотеку и ускорить установку зависимостей.

Что не так не знаю, ибо ошибка в 71 строке и что в этой строке — ХЗ.

п.с. для форматирования кода есть символы «``` код на новой строке, перенос строки ```»

**Comment by snegokmf** [comment]
Здравствуйте, сам как-то столкнулся с данной проблемой. Как понял, ситуация связанна с вебпаком. Для себя решил задачу подключением jQuery из cdn, глобально без объявления `const $ = require('jQuery')` . Правда, не уверен на сколько правильный данный подход.

**Comment by Webrote** [comment]
Да, как вариант, если не получится найти другого решения.
Только не очень понятно, почему в моем случае вылезает ошибка, так как проверял js файл на выходе и там были обе библиотеки- и jquery и  owl.carousel.
