### ISSUE TITLE
Подключение сторонних плагинов

### ISSUE THREAD

**Issue by testuser03** [nicothin/NTH-start-project#86]
Николай, здравствуйте! Подскажите как в вашей системе правильно подключать сторонние плагины, а именно их css файлы?

Установил simblebar через npm в раздел dependencies.
JS подключил реквайром в нужном блоке (как отдельный simplebar блок я не создавал) - работает, а стили не соображу как включить.
Так не собирает вообще, ибо ругается что файл не находит.
```javascript
"addStyleBefore": [
    "node_modules/simplebar/dist/simplebar.css",
    ...
],
```

Пока подключаю таким образом
```javascript
"addAssets": {
    "node_modules/simplebar/dist/simplebar.css": "css/libs",
    ...
  },
```
и в layout.pug обычным линком подключаю из билда
работает, но почему то ощущение что я "вошел через окно"

**Comment by nicothin** [comment]
К примеру, вот так:
```
  "addStyleBefore": [
    "src/scss/variables.scss",
    "src/scss/mixins.scss",
    "../../node_modules/simplebar/dist/simplebar.css",
  ],
```

**Comment by nicothin** [comment]
[теперь](https://github.com/nicothin/NTH-start-project/commit/174a655f28683e5c94c8491d8e8e15bb844589ab) можно и так:
```
  "addStyleBefore": [
    "src/scss/variables.scss",
    "src/scss/mixins.scss",
    "simplebar/dist/simplebar.css",
  ],
```
