### ISSUE TITLE
Что уже должно быть установлено?

### ISSUE THREAD

**Issue by astrakhanRinat** [nicothin/NTH-start-project#89]
Привет. Прошу помочь разобраться. Я пытался установить зависимости на своем ноуте. Выдает ошибки что не хватает компонентов, не достаточно прав. Система Убунту, устанавливал через судо. Я новичок )

**Comment by nicothin** [comment]
Зависимости ставятся без sudo.
Должен быть установлен nodejs.
Без скрина ошибки точно ничего нельзя сказать об ошибке.

**Comment by astrakhanRinat** [comment]
Приложил скриншот. Пытался сделать как пишут здесь -
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
Не
помогло (

сб, 27 апр. 2019 г. в 12:11, Nikolay Gromov <notifications@github.com>:

**Comment by nicothin** [comment]
>Приложил скриншот.

нет.

**Comment by astrakhanRinat** [comment]
С празником Пасхи! Пробую еще раз, спасибо за терпение )

сб, 27 апр. 2019 г. в 22:53, Nikolay Gromov <notifications@github.com>:

**Comment by astrakhanRinat** [comment]
Проблема решена установкой nvm. Спасибо. Чайники они такие чайники )

вс, 28 апр. 2019 г. в 07:12, Rinat Mambetov <astrakhan.rinat@gmail.com>:
