### ISSUE TITLE
Зависает экран при вызове модального окна

### ISSUE THREAD

**Issue by MaxVilson** [nicothin/NTH-start-project#9]
Здравствуйте Николай!
Спасибо большое за данный шаблон, во многом он мне облегчил мою работу.
Я нашел "баг", при вызове модального окна, экран зависает и пропадает вертикальный скролл. Подскажите пожалуйста, как можно исправить данный "баг"?

**Comment by nicothin** [comment]
Вижу, спасибо.
Сейчас посмотрим как это поправить.

**Comment by nicothin** [comment]
https://github.com/nicothin/NTH-start-project/commit/611b6d6499d3280a0b191732952fad1fe5aa5980
