### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by adm1t** [nicothin/NTH-start-project#91]
Крашится компиляция стилей при отстутствии файла .scss у блока, который прописан в конфиге в секции 'alwaysAddBlocks'. 

![Снимок](https://user-images.githubusercontent.com/26100455/59260593-952e1200-8c44-11e9-8884-dd7bc4443934.JPG)

**Comment by nicothin** [comment]
https://github.com/nicothin/NTH-start-project/commit/074321ee68105aa4b12727df5cd2112cbb3e043e
