### ISSUE TITLE
Ошибка при выполнении head-script.js

### ISSUE THREAD

**Issue by smargelov** [nicothin/NTH-start-project#95]
В head-script.js на 27 строке требуется body, который ещё не создан в DOM, так как скрипт вызывается до появления body. Это вызывает ошибку document.body is null

**Comment by nicothin** [comment]
Исправил, проверьте пожалуйста.
Внимание: параллельно чуть поменял имя css custom properties, указывающей ширину скролла.
https://github.com/nicothin/NTH-start-project/commit/582ef22c0617390d4eae531c0647594a423fd726

**Comment by smargelov** [comment]
Спасибо. Всё работает
