### ISSUE TITLE
Для чего нужна папка bg-img в блоках, если изображения с неё не попадают в сборку?

### ISSUE THREAD

**Issue by Webica** [nicothin/NTH-start-project#97]
Собственно описание вопроса в заголовке :)

**Comment by nicothin** [comment]
Для того, чтобы хранить в ней svg, вставляющиеся фонами в стили. 

Такие картинки пишутся прямо внутрь стилей посредством [postcss-inline-svg](https://github.com/TrySound/postcss-inline-svg), имеющимся в сборке.
